### model
# model_name_or_path: THUDM/glm-4-9b
model_name_or_path: THUDM/chatglm3-6b
quantization_bit: 4
trust_remote_code: true

### resume
resume_from_checkpoint: saves/checkpoint-500
resume_lora_training: true

### method
stage: sft
plot_loss: true
do_train: true
finetuning_type: lora
lora_rank: 4
lora_target: all

# deepspeed: examples/deepspeed/ds_z3_config.json
# use_reentrant: true

### dataset
dataset: sfzy_train
dataset_dir: ./data
val_size: 0.1
template: chatglm3
cutoff_len: 8192
max_samples: 15000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/chatglm3-6b/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
fp16: true
ddp_timeout: 180000000

report_to: none
run_name: test_run # 可选

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
